version: '3'

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    network_mode: host
    volumes:
      - ./config:/config
      - ./media:/media
    group_add:
      - render
    devices:
    # For AMD radeon
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped

